name: pull_request
on:
    pull_request:
        branches:    
          - master
jobs: 
    pull_request:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0
          - name: npm_install
            run: npm ci
          - name: run_tests
            run: npm run test-ci
