name: release
on:
  push:
    tags:
      - v[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write 
    steps:
    - uses: actions/checkout@v3
    - run: echo CHANGELOG=$(git log --oneline `git tag -l | sort -r | head -n 1`..HEAD) >> $GITHUB_ENV
    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        body: ${{ env.CHANGELOG }}
    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CHANGELOG: ${{ env.CHANGELOG }}
      with:
        filename: .github/ISSUE_TEMPLATE.md
        update_existing: true
        search_existing: all
